### ISSUE TITLE
go get报错

### ISSUE THREAD

**Issue by kaousi** [k8gege/LadonGo#4]
go: github.com/k8gege/LadonGo imports
        github.com/k8gege/LadonGo/mysql imports
        github.com/Go-SQL-Driver/MySQL: github.com/Go-SQL-Driver/MySQL@v1.5.0: parsing go.mod:
        module declares its path as: github.com/go-sql-driver/mysql
                but was required as: github.com/Go-SQL-Driver/MySQL

**Comment by k8gege** [comment]
> 
> 
> go: github.com/k8gege/LadonGo imports
> github.com/k8gege/LadonGo/mysql imports
> github.com/Go-SQL-Driver/MySQL: github.com/Go-SQL-Driver/MySQL@v1.5.0: parsing go.mod:
> module declares its path as: github.com/go-sql-driver/mysql
> but was required as: github.com/Go-SQL-Driver/MySQL

**fixed**
