### ISSUE TITLE
macos报错

### ISSUE THREAD

**Issue by nelly2340** [k8gege/LadonGo#5]
go/pkg/mod/github.com/k8gege/!ladon!go@v0.0.0-20210327063709-ea782c6965e3/install.go:25:6: main redeclared in this block
	previous declaration at go/pkg/mod/github.com/k8gege/!ladon!go@v0.0.0-20210327063709-ea782c6965e3/Ladon.go:184:6

第一次接触go语言，装一个晚上，我疯了啊

**Comment by kaka77** [comment]
+1

**Comment by morganliup** [comment]
+1

**Comment by li-baige** [comment]
+1
